name: Bump Version

on:
  push:
    branches: [main]

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

jobs:
  bump-version:
    name: "Bump Version on main"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cat package.json
        run: cat ./package.json
      - name: Nodejs Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          target-branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: cat package.json again
        run: cat ./package.json
      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
