name: Bump Version

on:
  push:
    branches: [main]

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

jobs:
  bump-version:
    name: "Bump Version on main"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_PAT }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          node-version: 14
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          target-branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
