name: Build and Release
on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Nodejs Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Create packages
        run: npm run make
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: out/make/**/*.*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/make/squirrel.windows/x64/alpha-badger*.*
            out/make/zip/darwin/x64/alpha-badger*.*
